# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
